---
#-------------------------------
# General Site Settings

title: início
logo:
author: Thiago Martins Carvalho de Medeiros
description: this is meta description
email: cientistadedadosthiago@outlook.com
phone: +880 2544 658 256
address: São Paulo - Brasi
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: Sobre, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contato, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Olá! Eu sou <br> Thiago <br> Cientista de Dados
social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/engenheirothiagomedeiros/" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Bem-vindo ao meu portfólio! Aqui, você explorará minha jornada acadêmica e descobrirá minhas habilidades por meio de projetos fascinantes. Navegue pela seção de projetos, conecte-se através dos links das redes sociais, conheça minha trajetória na seção "Sobre" e mergulhe no mundo dos dados no meu blog, onde compartilho estudos, pesquisas e insights. Vamos explorar juntos o vasto universo da Ciência de Dados!

blurb-btn-link: "/about"
blurb-btn-name: SAIBA MAIS

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Habilidades
skills:
  - { name: Estatística e Matemática, color: "#fdb157", value: "90%" }
  - { name: Linguagens de Programação, color: "#9473e6", value: "60%" }
  - { name: Conhecimentos de Negócio, color: "#bdecf6", value: "80%" }
  - { name: Excel/MS Power BI, color: "#ffbcaa", value: "70%" }
  - { name: Machine Learning, color: "#ffbcaa", value: "10%" }

#-------------------------------
# Exprerience Section

experience-title: Experiência
experience:
  - {
      name: Junior UX Designer,
      icon: "icon-1.png",
      date: "Jan 2007 - Feb 2009",
      organization: "WEBEX",
    }
  - {
      name: UX & UI Designer,
      icon: "icon-2.png",
      date: "Mar 2009 - Aug 2014",
      organization: "AUGMEDIX",
    }
  - {
      name: Senior UI Designer,
      icon: "icon-3.png",
      date: "Sep 2014 - Present",
      organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Formação Acadêmica
education:
  - {
      name: Engenharia de Produção,
      date: "2018",
      organization: "Universidade São Judas Tadeu",
    }
  - {
      name: Pós Graduação - BI - Big Data - Analytics - Ciência de Dados,
      date: "2022",
      organization: "Universidade Anhanguera",
    }
  - {
      name: Introdução à Ciência de Dados,
      date: "2023",
      organization: "Fundação Getúlio Vargas",
    }
  - {
      name: Formação Python,
      date: "2021",
      organization: "Alura",
    }

#-------------------------------
# Services Section

services-title: Serviços
Serviços:
  - {
      name: Analise de Dados,
      icon: ti-palette,
      description: "Coleta e limpeza de dados, exploração de dados e análise estatística.",
      active: ,# Add true to select section
    }
  - {
      name: Desenvolvimento de Modelos Preditivos,
      icon: ti-vector,
      description: "Machine Learning com aplicação de algoritmos de classificação, regressão, agrupamento. Otimização de modelos para fornecer  previsões precisas e generalizáveis para novos conjuntos de dados.",
      active: true, # Add true to select section
    }
  - {
      name: Comunicação de Resultados e Tomada de Decisão,
      icon: ti-panel,
      description: "Elaboração de dashboards, relatórios e apresentações para visualização de dados, storytelling e colaboração interdisciplinar.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
